In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
df=pd.read_excel('Rehab Referral Case-Insights Career.xlsx',sheet_name='data')
print('data has been successfully imported')

data has been successfully imported

In [2]:
df.columns

Index(['clmadmitper', 'clmseprtid', 'prvnbr', 'hospgrp', 'hospstate',
       'medprvnbr', 'mbrage', 'patientgender', 'drggrpv6x', 'cmbsmed',
       'ClmSeprtType', 'clmlosdays', 'medicoutofpktamt',
       'totfundhospmedbenefitamt', 'clmicudays', 'dischrgtype',
       'specialty_grp', 'rehab_xfer_flg', 'r28_flg', 'episode28d_chg',
       'hacofadj1_flg', 'ClmAdmitDt', 'ClmDischrgDt', 'dischrghm_flg',
       'flg_complex', 'rehab_clmseprtid', 'rehab_prvnbr', 'rehab_hospgrp',
       'rehab_clmadmitdt', 'rehab_ClmDischrgDt', 'rehab_ClmSeprtType',
       'rehab_ClmLOSDays', 'rehab_hosptype', 'rehab_days2readmit',
       'rehab_HospExProsBen', 'totmotoradmitfim', 'totmotordischargefim',
       'totcogadmitfim', 'totcogdischargefim', 'totdischargefim',
       'totadmitfim'],
      dtype='object')

In [50]:
#1 count the number of separations, sum up the total benefits paid, average charge price,count the number of
#unique hospitals by each hospital group,sorted by the descending order of average charging price$

df.groupby(['hospgrp'],as_index=False).agg({'clmseprtid':'count','totfundhospmedbenefitamt':'sum',\
                                            'episode28d_chg':'mean','prvnbr':'nunique'})\
.sort_values(by=['episode28d_chg'],ascending=[False])

,hospgrp,clmseprtid,totfundhospmedbenefitamt,episode28d_chg,prvnbr
4,Hospital Group 14,2,2.611360e+04,33923.445000,1
10,Hospital Group 2,472,9.842992e+06,25031.718814,2
2,Hospital Group 12,231,4.807711e+06,24730.419827,1
25,Hospital Group 33,188,3.818465e+06,23858.500426,2
5,Hospital Group 15,23,5.767942e+05,23505.965217,1
38,Hospital Group 7,26,4.801764e+05,23158.465769,1
37,Hospital Group 6,2472,5.613945e+07,21968.078208,4
0,Hospital Group 10,55,1.022301e+06,21638.576182,1
21,Hospital Group 3,931,2.113929e+07,21460.811944,2
26,Hospital Group 34,15,2.937828e+05,20421.330000,1
28,Hospital Group 36,488,1.030835e+07,20360.873463,3
40,Hospital Group 9,5209,1.143616e+08,19917.041428,30
3,Hospital Group 13,96,1.594669e+06,19553.730104,1
8,Hospital Group 18,43,8.927833e+05,19536.547209,1
39,Hospital Group 8,1246,2.481911e+07,19446.878997,14
34,Hospital Group 41,3874,8.095988e+07,19232.778872,7
30,Hospital Group 38,149,2.863636e+06,18842.121544,2
31,Hospital Group 39,10485,2.173266e+08,18526.482892,43
36,Hospital Group 5,102,1.917428e+06,18511.235686,2
12,Hospital Group 21,123,2.197887e+06,17640.008862,1
35,Hospital Group 42,1241,2.674949e+07,17570.596390,5
24,Hospital Group 32,6,1.241376e+05,17341.961667,1
17,Hospital Group 26,11,2.171058e+05,17107.296364,1
32,Hospital Group 4,2577,5.445093e+07,16588.987237,8
15,Hospital Group 24,100,2.173808e+06,16564.869400,1
1,Hospital Group 11,167,3.432437e+06,16188.894072,1
33,Hospital Group 40,3101,6.263850e+07,15844.144447,12
29,Hospital Group 37,491,9.098141e+06,15529.750978,4
14,Hospital Group 23,54,9.189035e+05,15482.306667,1
9,Hospital Group 19,177,3.889923e+06,15092.820056,1
6,Hospital Group 16,6,1.137635e+05,15052.113333,1
13,Hospital Group 22,226,4.388384e+06,14953.567168,1
27,Hospital Group 35,332,6.762246e+06,14733.261988,1
20,Hospital Group 29,321,6.211891e+06,14663.797913,1
7,Hospital Group 17,140,2.814065e+06,14589.246929,1
11,Hospital Group 20,243,4.651089e+06,14551.833251,1
22,Hospital Group 30,10,1.518366e+05,13410.053000,1
18,Hospital Group 27,107,1.891245e+06,13311.105794,1
19,Hospital Group 28,5,6.811088e+04,13267.526000,1
16,Hospital Group 25,16,2.707701e+05,12162.655000,1
23,Hospital Group 31,47,8.860517e+05,11609.284681,1

In [52]:
#2 count the number of separations, the average length of stay, average ICU days, average benefits paid by hospital 
#acquired complexity flag,sorted by the descending order of average benefit paid$

df.groupby(['hacofadj1_flg'],as_index=False).agg({'clmseprtid':'count','clmlosdays':'mean','clmicudays':'mean',\
                                                  'totfundhospmedbenefitamt':'mean'})\
.sort_values(by=['totfundhospmedbenefitamt'],ascending=[False])

   hacofadj1_flg  clmseprtid  clmlosdays  clmicudays  totfundhospmedbenefitamt
1              1         369    9.910569    0.235772              24477.567425
0              0       35239    5.454695    0.049377              20950.072421

In [55]:
#3 count the number of patients did surgery by genders, and also count the number of patients did rehab by genders. 
#in the end, find rehab rate of each gender (rehab rate is the percentage % of patients choose rehab treatments 
#after their acute surgeries. )

table1=df.groupby(['patientgender']).agg({'clmseprtid':'count','rehab_clmseprtid':'count'})
table1['rehab_rate']=table1.rehab_clmseprtid/table1.clmseprtid
table1

               clmseprtid  rehab_clmseprtid  rehab_rate
patientgender
F                   20162              9938    0.492907
M                   15446              5337    0.345526

In [4]:
#Python Homework2 -- find out outliers
#Data extraction:
#step1: Use ‘describe’ function to find the mean and standard deviation of the length of stays in hospital separation
#step2: extract all the data with length of stay outliers：
#length of stay outlier is the ones when the length of stay is greater than （mean value+ 3*standard deviantion value）

df.loc[:,'clmlosdays'].describe()

count    35608.000000
mean         5.500871
std          3.227163
min          1.000000
25%          4.000000
50%          5.000000
75%          6.000000
max        156.000000
Name: clmlosdays, dtype: float64

In [8]:
df[df.clmlosdays>5.500871+3*3.227163]

,clmadmitper,clmseprtid,prvnbr,hospgrp,hospstate,medprvnbr,mbrage,patientgender,drggrpv6x,cmbsmed,...,rehab_ClmLOSDays,rehab_hosptype,rehab_days2readmit,rehab_HospExProsBen,totmotoradmitfim,totmotordischargefim,totcogadmitfim,totcogdischargefim,totdischargefim,totadmitfim
435,CS_2014-07_2015-06,210464803,Hospital 192,Hospital Group 41,NSW,MedPrv 296,82,F,I03B,49318,...,40.0,Private,0.0,19331.0,50.0,72.0,35.0,35.0,107.0,85.0
440,CS_2014-07_2015-06,210465889,Hospital 145,Hospital Group 40,VIC,MedPrv 614,71,F,I03B,49318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
753,CS_2014-07_2015-06,211205479,Hospital 134,Hospital Group 8,VIC,MedPrv 22,85,M,I03A,49315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
811,CS_2014-07_2015-06,211211090,Hospital 145,Hospital Group 40,VIC,MedPrv 103,72,M,I04A,49518,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,CS_2014-07_2015-06,211498432,Hospital 159,Hospital Group 39,NSW,MedPrv 196,78,F,I03B,49518,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35577,CS_2016-07_2017-06,259331534,Hospital 83,Hospital Group 39,QLD,MedPrv 225,88,M,I03A,49315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,CS_2016-07_2017-06,259571295,Hospital 189,Hospital Group 2,NSW,MedPrv 927,45,M,I03B,11700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35595,CS_2016-07_2017-06,259958301,Hospital 91,Hospital Group 9,QLD,MedPrv 591,79,F,I03A,47522,...,28.0,Private,0.0,11382.0,25.0,44.0,29.0,29.0,73.0,54.0
35602,CS_2016-07_2017-06,260895057,Hospital 172,Hospital Group 39,NSW,MedPrv 8,75,F,I03A,49321,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35603,CS_2016-07_2017-06,261693347,Hospital 49,Hospital Group 39,WA,MedPrv 407,88,M,I03A,49321,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN